### ISSUE TITLE
Slow when first loading with wpf

### ISSUE THREAD

**Issue by musictopia2** [jspuij/BlazorWebView#17]
I used the default sample.  However, I found that unless I wait a few minutes to do something, when i click the counter for example, it does nothing for quite a while and i can't navigate to any of the other pages.  Hopefully there is a way to improve startup performance so when the page loads and you go to the counter page, then its responsive right away.

**Comment by jspuij** [comment]
Hi musictopia. I've just checked https://github.com/jspuij/BlazorWebViewTutorial/tree/5_wpf (after I've upgraded it to BlazorWebView 0.2.0-preview8) and I don't experience any slowdown. It's instantly available. Could you create a minimal repro and/or provide some more information about your environment? (E.g. whether you are using the old edge or the new edge and which version number).

**Comment by musictopia2** [comment]
How do I know if i am using new edge or old edge.  What would always duplicate the problem on my end is using the tutorial with no code changes.

**Comment by jspuij** [comment]
You can replace BlazorWebView with BlazorOldEdgeWebView to use the old edge (should always be there), and you can replace BlazorWebView with BlazorNewEdgeWebView to use the new edge (could be that it is not installed, in that case it won't load.) The minimum version for the new edge is 84. (probably canary).

**Comment by jspuij** [comment]
I've tested both the old and new edge here on to be sure, but no slowdowns.
Could you checkout this branch from the tutorial repo:  https://github.com/jspuij/BlazorWebViewTutorial/tree/5_wpf . It's exactly the tutorial code.

**Comment by musictopia2** [comment]
Did you set default to wpf.  Because when I downloaded the new sample, it showed starting with client.  Client has no problems.  However, when I set default to wpf and try, then the slowdown happens unless i wait a little while.  Not sure if there is a way you can do logging to get hints of why i am having problems on my end.  After a while, its okay.  However, if i go to the counter right away and click the button, then nothing happens and it won't do anything when i click another link either.  If I run the client and not wpf, then no problem.

**Comment by musictopia2** [comment]
I just saw where i can use old or new.  I tried to use the old and still same problem.  Then I tried the new and got a runtime error.   I am guessing its possible that i am using a version of edge that is so old that even your old causes it to be slow.  Is it even possible for me to update my edge?  How do i find out the exact version of the edge i have?

**Comment by jspuij** [comment]
For the "old edge", it's tied to the windows version. There must be an about box somewhere to request it. I'd like to know the version, so that I can reproduce it. 
The list of versions is here: https://en.wikipedia.org/wiki/Microsoft_Edge

For the new edge, you'd have to download it. It can be downloaded here:

https://www.microsoftedgeinsider.com/en-US/download

Now, unfortunately due to Corona, a release was skipped and for the SDK I'm using, the edge version was not released yet. You need at least 84.0.488. Currently that is dev channel or canary.

Let me know what your old edge version is, and whether installing the dev or canary new edge solves it.

**Comment by musictopia2** [comment]
Good news is i was able to find it.  showed as
44.18362.449.0

**Comment by musictopia2** [comment]
I downloaded the release 84.  After downloading that, it worked find if using either the original or new.  If using old, then same problem.  I am guessing the solution would be to update the tutorials and make it clear a person must have at least release 84 for it to work.  I found a way to download the official version which was 83 but still had same problems but the dev which is release 84 fixed it as long as i use either new or the original one but not old.

**Comment by jspuij** [comment]
There is a note at the top ;-)
https://jspuij.github.io/BlazorWebView.Docs/pages/wpftutorial.html?tabs=addwpf-1

Anyway, could you post your windows version so that I can have a look at the old edge? Old edge works fine on the latest windows 10 (as I'm running that), but I want to try and reproduce your problem.

**Comment by musictopia2** [comment]
How do i find out which version of windows i am running?

**Comment by musictopia2** [comment]
The oldest edge was replaced by version 83.  The old one was 44.  Currently i have 2 edges (83 and 84).
