### ISSUE TITLE
Race condition in BlazorWebViewHost.cs intermittently prevents web window from opening

### ISSUE THREAD

**Issue by budcribar** [jspuij/BlazorWebView#19]
This is the same issue as I found with SteveSanderson's web window. 

I found a race condition and isolated it to line 148 of BlazorWebViewHost.cs. If you insert a Thread.Sleep(2000) you will see it consistently as the task on line 143 does not get through enough initialization before the code on line 160 WebWindow.NavigateToUrl(BlazorAppScheme + "://app/"); gets executed.

i.e. Task.Factory.StartNew(async () =>
{
try
{
               var ipc = new IPC(BlazorWebView);

                Thread.Sleep(2000);
                await RunAsync<TStartup>(ipc, appLifetimeCts.Token);

            }
            catch (Exception ex)
            {
                UnhandledException(ex);
                throw;
            }
        });
will prevent the web window from initializing correctly.

This seems to fix the problem. But further investigation is needed
.
.
.
        var completed = new ManualResetEventSlim();

        CancellationTokenSource appLifetimeCts = new CancellationTokenSource();
   

        Task.Factory.StartNew(async () =>
        {
            try
            {
                var ipc = new IPC(BlazorWebView);

                Thread.Sleep(2000);
                await RunAsync<TStartup>(ipc, appLifetimeCts.Token, completed);

            }
            catch (Exception ex)
            {
                UnhandledException(ex);
                throw;
            }
        });

        try
        {
            completed.Wait();
            WebWindow.NavigateToUrl(BlazorAppScheme + "://app/");
           
            WebWindow.WaitForExit();
        }
        finally
        {
            appLifetimeCts.Cancel();
        }
    }
.....

private static async Task RunAsync(IPC ipc, CancellationToken appLifetime, ManualResetEventSlim completed)
{

        var configurationBuilder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: true);

        JSRuntime = new PlatformJSRuntime(ipc);
        completed.Set();
        await PerformHandshakeAsync(ipc);

        
The ManualResetEventSlim will prevent the WebWindow.NavigateToUrl from running until DesktopJSRuntime has been initialized. This seems to fix the problem but I'm not sure if there are other issues or not with the race between NavigateToUrl and RunAsync.

I found this because I am re implementing  IBlazorWebView to be able to open a webview on a remote host and it fails every time.

**Comment by jspuij** [comment]
This does not make a lot of sense for a local instance of BlazorWebView because the initialization code inside IPC and JSRuntime is essentially only the constructors. So the task scheduling would have to be so slow that it is longer than the load of the web page + client side scripts by the browser.

My feeling is that this is a race condition that is introduced by the fact that you're doing some stuff remotely. However the fix seems reasonable, so I'll include it in a new version.

May I ask what you're doing to open a remote host? The whole idea of BlazorWebView is to run the app within the webview without a webserver on a native .net runtime.

Or is it your intention to get all code from a webserver, loading assemblies dynamically, so that you can distribute it through the web without an appstore? Because that's kind of cool ;-)

**Comment by budcribar** [comment]
I have a diagnostic application that lives on a manufacturing system behind a firewall. The goal is to enable a switch to send the user interface via GRPC to a server that I can log into and interact with the user interface. Next up, I want to interact with the GRPC server with a web browser and then be able to control the diagnostic app running on a manufacturing system in Taiwan from my cell phone. Since Steve has all but abandoned the WebWindow project, I'm counting on you :) I'm in the process of porting from Steve's project to yours and I may need a couple of more small changes. I can also give you a demo if you are interested.

**Comment by jspuij** [comment]
I have no insight in the requirements, so I'm just guessing here, but wouldn't it be simpler to either:

1) use server side blazor, have code at the server side and tunnel http + websockets through some sort of firewall. Then you can use a normal webbrower / webview for the platform.
2) use the stock Blazorwebview, but use gRPC to control the diagnostics application through an API. The code lives on the cell phone then.

I don't see the need for remoting the IPC channel. To me it feels a bit that you are rebuilding Server Side Blazor based on gRPC instead of signalR. However, all the bits in this repo (and Steve's) are mostly from the WASM variant of blazor and less suitable for a client-server architechture.
